changes with basic calculations
JanVan01/herd-behaviour-model pull request #6
Opened 2017-01-26 11:20 UTC by joanago

2017-01-27 11:15 UTC, JanVan01 requested changes

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +    set g-dir [0 0]
Alle Turtles können die gleiche g-dir haben. Die Entscheidung ob diese dann genutzt wird geht dann über das weight. Also kann das hier einmal für alle gesetzt werden und muss später nicht überschrieben werden.

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +  ;;temp ;; help temporary vector (array)
kann glaube ich weg

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +    let base [0 0] ;; base of function calculated in every
nicht aussagekräftig
Kommentar nicht vollständig

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +    let ci-dir array:from-list (list xcor ycor) ;; the position vector of actual turtle
`let ci c`
sollte reichen
Ich würde auch eher c als c-dir benutzen, da es sich ja nicht um einen Richtungsvektor handelt

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +to-report multiply-vector-number[arr num] ;; calculates a vector * -1
Copy and paste comment

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +to-report minus-one[arr] ;; calculates a vector * -1
Ist nur ein Sonderfall von `multiply-vector-number`

2017-01-27 11:15 UTC, JanVan01 commented on herd_behaviour.nlogo
> +to-report calculate-base[ci-dir cj-dir];; formula 2 in paper
`calculate base`?

2017-01-28 10:22 UTC, JanVan01 commented on herd_behaviour.nlogo
> +      if w != 0[
Was passiert hier? Das ist immer noch der Ausweichfall. Da hat die prefered direction keinen Einfluss

2017-01-28 11:31 UTC, joanago commented on herd_behaviour.nlogo
> +    let base [0 0] ;; base of function calculated in every
hab function vergessen... diese funktion, die wir festgelegt haben, die in jeder gleichung gerechnet werden muss.

2017-01-28 11:31 UTC, joanago commented on herd_behaviour.nlogo
> +  ;;temp ;; help temporary vector (array)
rechne später mit g-dir

2017-01-28 11:35 UTC, joanago commented on herd_behaviour.nlogo
> +    set g-dir [0 0]
ok

2017-01-28 11:36 UTC, joanago commented on herd_behaviour.nlogo
> +    let ci-dir array:from-list (list xcor ycor) ;; the position vector of actual turtle
hatte einfach ci benutzt weil das auch so in der gleichung im paper steht, dort wird zwischen ci für den eigenen und cj für den der anderen in der gleichung unterschieden

2017-01-28 11:37 UTC, joanago commented on herd_behaviour.nlogo
> +to-report minus-one[arr] ;; calculates a vector * -1
jap, kannst du ändern

2017-01-28 11:37 UTC, joanago commented on herd_behaviour.nlogo
> +to-report multiply-vector-number[arr num] ;; calculates a vector * -1
ups, nicht gründlich gearbeitet

2017-01-28 11:38 UTC, joanago commented on herd_behaviour.nlogo
> +to-report calculate-base[ci-dir cj-dir];; formula 2 in paper
calculate-base ist die funktion, die wir für alle brauchen, die basis der funktionen, die in allen drei gleichungen im paper benutzt wird

2017-01-28 11:40 UTC, joanago commented on herd_behaviour.nlogo
> +      if w != 0[
das ist die realisation der ersten gleichung im paper, formular 1. falls das falsch so ist, gerne ändern, d-dir ist die richtung die am ende für alle, je nach fall 1 ausweichen, 2 folgen oder 3 für informed mit prefered direction ausweichen oder folgen, berechnet wird

2017-01-28 13:42 UTC, joanago commented on herd_behaviour.nlogo
> +  ;;temp ;; help temporary vector (array)
*d-dir

2017-01-28 13:44 UTC, joanago commented on herd_behaviour.nlogo
> +to-report minus-one[arr] ;; calculates a vector * -1
hab ich geändert :)

2017-01-28 15:02 UTC, MilanMilanMilan commented on herd_behaviour.nlogo
> +    set g-dir [0 0]
Das passt auch zur Beschreibung im setup

2017-01-28 15:51 UTC, MilanMilanMilan commented on herd_behaviour.nlogo
> +      if w != 0[
Ich hätte es so verstanden, dass sich die erste Formel ausschließlich in Abhängigkeit der auszuweichenden Nachbarn berechnet, also ohne bevorzugte Richtung.

2017-01-28 20:20 UTC, JanVan01 commented on herd_behaviour.nlogo
> +  ;;temp ;; help temporary vector (array)
Das temp meine ich

2017-01-28 20:22 UTC, JanVan01 approved these changes

2017-01-28 20:22 UTC, merged