accuracy and deviation angles
JanVan01/herd-behaviour-model pull request #8
Opened 2017-02-02 12:21 UTC by joanago

2017-02-07 19:18 UTC, JanVan01 requested changes
Die Konflikte müssen noch gefixt werden

2017-02-08 12:29 UTC, AliceBalfanz approved these changes

2017-02-08 15:45 UTC, MilanMilanMilan approved these changes

2017-02-08 15:49 UTC, JanVan01 commented on herd_behaviour.nlogo
> +=======
remove please

2017-02-08 15:50 UTC, JanVan01 approved these changes

2017-02-08 17:35 UTC, merged